### ISSUE TITLE
Add "Fork me on Github" banner

### ISSUE THREAD

**Issue by Tset-Noitamotua** [robotframework/foundation#3]
I recommend adding such a banner to robotframework.org because for first time visitors of  the site it is not obvious that RF is open source until they read the description.

![image](https://cloud.githubusercontent.com/assets/5635462/23657613/35664d3c-033f-11e7-9e3b-a5c0da8e1ffb.png)

**Comment by Tattoo** [comment]
I feel that this banner should not be added. 

First of all, as you said it reads right there in the description -- I don't see what benefit does this bring to the table? Why would people need to _immediately_ know this is an open source project without reading any text? 

Second of all, I feel that the design of the banner does not fit the current style of the site. Either one would need to be modified,  so adding this would be more work than just adding some css easily. And since I don't see why we would want this in the first place, I really am not feeling to do so unless someone gives me good enough reason.

**Comment by pekkaklarck** [comment]
I agree with @Tattoo. Third reason for me not liking this banner is that there isn't just a single project you can fork. Pages at http://robotframework.org are for the whole ecosystem that consists of various projects, not for the core framework only.
